---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_solo
  environments_path: environments
  chef_license: accept-no-persist
  solo_rb:
    file_atomic_update: false

platforms:
- name: centos-7-chef-12
  driver_config:
    image: centos/systemd
    run_command: /usr/sbin/init
    provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service
    - yum update -y
    - yum install epel-release -y
    - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
    - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12 && rm install.sh

- name: centos-7-chef-13
  driver_config:
    image: centos/systemd
    run_command: /usr/sbin/init
    provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service
    - yum update -y
    - yum install epel-release -y
    - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
    - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh

- name: centos-7-chef-latest
  driver_config:
    image: centos/systemd
    run_command: /usr/sbin/init
    provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service
    - yum update -y
    - yum install epel-release -y
    - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
    - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 14 && rm install.sh

- name: centos-69-chef-12
  driver_config:
    image: centos:6.9
    provision_command:
    - yum update -y
    - yum install epel-release -y
    - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
    - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12 && rm install.sh

suites:
  - name: default
    run_list:
      - recipe[certie::default]
      - recipe[certie::selfsigned]
    attributes:
      certie:
        email: "devops@devops.com"
        organization: "Devops Limited"
        domains:
          happyslap.com:
            - happyslap.com
            - www.happyslap.com
            - staging.happyslap.com
          orange.com:
            - orange.com
